sources:
  - name: job_ads
    schema: staging
    tables:
      - name: stg_ads # smeknamn
        identifier: job_ads # namnet i databasen
      - name: stg_skill # smeknamn
        identifier: job_ads__must_have__skills # namnet i databasen